remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  back_home_text: "go back.."
  appearance_toggle: true 
  date_format: "%Y-%m-%d"
  show_description: false 
  show_navbar: true # show h orizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
